baseURL = "https://shittydev.com"
theme = "risotto"
title = "shittydev.com"
author = "Kevin Alavik"
copyright = "© [Kevin Alavik](https://github.com/KevinAlavik)."
paginate = 3
languageCode = 'en-us'
contentDir = 'content'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true
sectionPagesMenu = "main"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10


[params]
noindex = false

[params.theme]
palette = "base16-dark"

[params.about]
title = "shittydev.com"
description = "A pretty awesome blog"
logo = "🇸🇪"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/KevinAlavik"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:kevin@alavik.se"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel   = 3
        ordered    = true
